
server:
  tomcat:
    threads:
      min-spare: 10  #最小线程数，默认值就是10
      max: 20    #最大线程数，默认值是200
    max-connections: 30 #同一时间，tomcat允许能连接的最大数, 默认值是 8192。注意：这个属性是属于tomcat的
    accept-count: 10   #最大等待数，默认值是 100。 tomcat同时可以处理的请求就是 [8192 + 100 = 8292]，这个属性是属于tomcat的
    #connection-timeout: 3000 #连接超时时间3s,默认是20s

#查看更加详细的tomcat日志
#logging:
#  level:
#    org:
#      apache:
#        tomcat: DEBUG